# Creating Series

In [ ]:
#Vivek kolpe

In [3]:
# Program for creating Series using series() method of Pandas Library

In [4]:
#Import Pandas library
import pandas as pd

In [5]:
#Creating Student Name List
Name=["Ashish","Sagar","Shrikant","Lovly","Saurabh"]
Name

['Ashish', 'Sagar', 'Shrikant', 'Lovly', 'Saurabh']

In [6]:
#Creating a Series 
Roll_list=pd.Series(Name,index=[1,2,3,4,5])
print(Roll_list)

1      Ashish
2       Sagar
3    Shrikant
4       Lovly
5     Saurabh
dtype: object

# Creating Data Frame

In [51]:
#Import Pandas library
import pandas as pd

In [52]:
#Creating Data Frame
df=pd.DataFrame([[10,12,14,16],[11,18,15,21],[12,13,14,15]],
columns= ["CD","DBMS","DSS","CAO"])

In [53]:
df

   CD  DBMS  DSS  CAO
0  10    12   14   16
1  11    18   15   21
2  12    13   14   15

In [54]:
df.shape

(3, 4)

In [55]:
df.size

12

In [56]:
df.ndim

2

# Adding Record (Row) to the data frame

In [63]:
df2=pd.DataFrame([[5,6,7,8]],
columns= ["CD","DBMS","DSS","CAO"])

In [79]:
df3=df.append(df2,ignore_index=True)

In [80]:
df3

   CD  DBMS  DSS  CAO
0  10    12   14   16
1  11    18   15   21
2  12    13   14   15
3   5     6    7    8

# Adding Attribute (Columns) name DM

In [84]:
df3["DM"]=[12,15,16,14]

In [85]:
df3

   CD  DBMS  DSS  CAO  DM
0  10    12   14   16  12
1  11    18   15   21  15
2  12    13   14   15  16
3   5     6    7    8  14

# Deleting Record from  df3 dataframe

In [89]:
df4=df3.drop(index=[1])

In [90]:
df4

   CD  DBMS  DSS  CAO  DM
0  10    12   14   16  12
2  12    13   14   15  16
3   5     6    7    8  14

# Deleting Attribute (Columns) from df3 dataframe

In [91]:
df5=df3.drop(columns=["DM"])

In [92]:
df5

   CD  DBMS  DSS  CAO
0  10    12   14   16
1  11    18   15   21
2  12    13   14   15
3   5     6    7    8

In [94]:
#Finding mean of DSS 

print("Mean of DSS:", df5["DSS"].mean())

Mean of DSS: 12.5

In [97]:
#Finding median of DSS

print("Median of DSS:", df5["DSS"].median())

Median of DSS: 14.0

In [98]:
#Finding mode of DSS

print("Mode of DSS:", df5["DSS"].mode())

Mode of DSS: 0    14
dtype: int64

In [99]:
#Finding max number of DSS

print("Max of DSS:", df5["DSS"].max())

Max of DSS: 15

In [100]:
#Finding Min number of DSS

print("Max of DSS:", df5["DSS"].min())

Max of DSS: 7