In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

In [2]:
import os

In [3]:
os.getcwd()

'C:\\Users\\hp\\Desktop\\Code\\ET - I Lab'

In [4]:
os.chdir("C:\\Users\\hp\\Desktop")

In [5]:
df=pd.read_csv("Salary_Data.csv")

In [6]:
df.head()

   YearsExperience  Salary
0              1.1   39343
1              1.3   46205
2              1.5   37731
3              2.0   43525
4              2.2   39891

In [7]:
df.tail()

    YearsExperience  Salary
25              9.0  105582
26              9.5  116969
27              9.6  112635
28             10.3  122391
29             10.5  121872

In [8]:
df.head(30)

    YearsExperience  Salary
0               1.1   39343
1               1.3   46205
2               1.5   37731
3               2.0   43525
4               2.2   39891
5               2.9   56642
6               3.0   60150
7               3.2   54445
8               3.2   64445
9               3.7   57189
10              3.9   63218
11              4.0   55794
12              4.0   56957
13              4.1   57081
14              4.5   61111
15              4.9   67938
16              5.1   66029
17              5.3   83088
18              5.9   81363
19              6.0   93940
20              6.8   91738
21              7.1   98273
22              7.9  101302
23              8.2  113812
24              8.7  109431
25              9.0  105582
26              9.5  116969
27              9.6  112635
28             10.3  122391
29             10.5  121872

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 2 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   YearsExperience  30 non-null     float64
 1   Salary           30 non-null     int64
dtypes: float64(1), int64(1)
memory usage: 608.0 bytes

In [10]:
df.describe()

       YearsExperience         Salary
count        30.000000      30.000000
mean          5.313333   76003.000000
std           2.837888   27414.429785
min           1.100000   37731.000000
25%           3.200000   56720.750000
50%           4.700000   65237.000000
75%           7.700000  100544.750000
max          10.500000  122391.000000

In [11]:
df.shape

(30, 2)

In [12]:
df.size

60

In [13]:
df.ndim

2

In [14]:
df.isnull().sum()

YearsExperience    0
Salary             0
dtype: int64

In [35]:
#Independent and Dependent Variables
#x = df['YearsExperience']
#y = df['Salary']

# Independent and Dependent Variables

In [44]:
X=df.drop('Salary',axis=1)

In [46]:
X.head()

   YearsExperience
0              1.1
1              1.3
2              1.5
3              2.0
4              2.2

In [45]:
y=df.Salary

In [47]:
y.head()

0    39343
1    46205
2    37731
3    43525
4    39891
Name: Salary, dtype: int64

In [48]:
from sklearn.model_selection import train_test_split

In [49]:
X_train,X_test,y_train,y_test=train_test_split(X,y,random_state=0,test_size=0.30)

In [50]:
print(X_train.shape)

(21, 1)

In [51]:
X_test.shape

(9, 1)

# Model Fitting

In [52]:
from sklearn.linear_model import LinearRegression
LR=LinearRegression()
LR.fit(X_train,y_train)

LinearRegression()

In [54]:
#Assigning Coefficient (slope) to m
m = LR.coef_

In [55]:
print("Coefficient  :" , m)

Coefficient  : [9360.26128619]

In [56]:
#Assigning Y-intercept to a
c = LR.intercept_

In [57]:
print("Intercept : ", c)

Intercept :  26777.391341197632

# y=mx+c

# Prediction

In [59]:
y_pred=LR.predict(X_test)

In [60]:
y_pred

array([ 40817.78327049, 123188.08258899,  65154.46261459,  63282.41035735,
       115699.87356004, 108211.66453108, 116635.89968866,  64218.43648597,
        76386.77615802])

In [61]:
y_test

2      37731
28    122391
13     57081
10     63218
26    116969
24    109431
27    112635
11     55794
17     83088
Name: Salary, dtype: int64

# Evaluation metrics

In [62]:
from sklearn import metrics

Accuracy

In [66]:
Accuracy = LR.score(X_test, y_test)
Accuracy

0.9740993407213511

MAE

In [67]:
print(metrics.mean_absolute_error(y_test,y_pred))

3737.4178618788987

MSE

In [68]:
print(np.sqrt(metrics.mean_squared_error(y_test,y_pred)))

4834.260936361728

RMSE

In [70]:
rmse = np.sqrt(metrics.mean_squared_error(y_test,y_pred))
print("RMSE:", rmse)

RMSE: 4834.260936361728